apiVersion: v1
kind: Service
metadata:
  name: jwt-backend-api-service
  namespace: jwt-backend-api
  labels:
    app.kubernetes.io/name: jwt-backend-api-service
    app.kubernetes.io/version: 1.0.0

spec:
  type: ClusterIP
  selector:
    app: jwt-backend-api

  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-backend-api-deployment
  namespace: jwt-backend-api
  labels:
    app.kubernetes.io/name: weather-api-deployment
    app.kubernetes.io/version: 1.0.0

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-backend-api

  template:
    metadata:
      labels:
        app: jwt-backend-api
      annotations:
        containeer.apparmor.security.beta.kubernetes.io/weather-backend-ctr: localhost/docker-default

    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsNonRoot: true
        runAsGroup: 10001
      containers:
        - name: jwt-backend-backend-ctr
          image: wozjac/jwt-backend-api:1.0.1
          resources:
            requests:
              cpu: 100m
              memory: 200M
            limits:
              cpu: 400m
              memory: 600M
          ports:
            - containerPort: 5000
          env:
            - name: JWT_BACKEND_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: jwt-backend-api-secret
                  key: PRIVATE_KEY_ID
            - name: JWT_BACKEND_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: jwt-backend-api-secret
                  key: CLIENT_EMAIL
            - name: JWT_BACKEND_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-backend-api-secret
                  key: PRIVATE_KEY
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            seccompProfile:
              type: RuntimeDefault
